[build-system]
requires = ["setuptools", "wheel"]
backend-path = ["installer"]
build-backend = "cppyy_monkey_patch:main"
[tool.pytest.ini_options]
markers = [
    "crashes: marks tests as crashing (deselect with '-m \"not crashes\"')",
]
